- name: converting dict into items
  hosts: localhost 
  vars:
   my_dict: 
    -linux
    -shell
    -ansible
  tasks:
  - name: converting dict into items
    ansible.builtin.debug:
     msg: "{{my_dict | items2dict}}"