- name: replace the word
- hosts: all
  vars:
    email_list: "john@example.com, jane@example.com, bob@example.com"
  tasks:
    - name: the replace the word
      ansible.builtin.debug:
        msg: "{{ email_list | regex_replace(',', ';') }}"
