- name: Convert date string to datetime object
  hosts: localhost
  vars:
    date_string: "2024-05-04 15:30:00"
  tasks:
    - name: Convert date string to datetime object
      debug:
        msg: "{{ date_string | to_datetime }}"
