- name: default
  hosts: all
  vars:
   greetings: "Hello,Everyone good morning"
  tasks:
  - name: default value when the variable not defined 
    ansible.builtin.debug:
     msg: "the course is {{course | default ('ansible')}} "
  - name: chnaging to capitalize the first string
    ansible.builtin.debug:
     msg: "{{greetings | capitalize}}"
