- name: default
  hosts: all
  vars:
   greetings: "Hello,Everyone"
  tasks:
  - name: default value when the variable not defined 
    ansible.builtin.debug:
     msg: "the course is {{course | default ('ansible')}} "
  - name: chnaging to uppercase
    ansible.builtin.debug:
     msg: "{{greetings | lower}}"
