- name: converting dict into items
  hosts: localhost 
  vars:
   my_dict: 
    course: ansible
    trainer: nagendrap
  tasks:
  - name: converting dict into items
    ansible.builtin.debug:
     msg: "{{my_dict | dict2items}}"