---
- name: inventory variables
  hosts: all
  tasks:
    - name: inventory variables using
      ansible.builtin.debug:
        msg: "hellow  webserver1 of the ennvrionment {{env}} and host ip is {{hostip}}"
