- name: inventory variables
  hosts: all
  tasks:
  - name: inventory variables using 
    ansible.builtin.debug:
     msg: "hellow hostip {{hostip}} of webserver1 of the ennvrionment {{ennvrionment}}"
