- name: register
  hosts: all
  tasks:
  - name: command execution to check ignore errors
    ansible.builtin.command: id expense 
    register: user
  tasks: 
   - name: to print the command output using register
     ansible.builtin.debug:
      msg: print output of user {{user}}
