- name: ignore errors 
  hosts: all
  tasks:
  - name: command execution to check ignore errors
    ansible.builtin.command: id expense 
    register: user
    ignore_errors: true
  tasks: 
   - name: to print the command output using register
     ansible.builtin.debug:
      msg: print output of user {{user}}
  tasks:
  - name: say hello
    ansible.builtin.debug:
     msg: "hi hello"