- name: top level variable 
  hosts: localhost
  vars:
   course: Devops
   trainer: nagenrda
   city: nellore
  tasks:
  - name: to run the top level variables 
    ansible.builtin.debug:
     msg: "Hi my name is {{trainer}} from {{city}} i will teach the {{course}}"
    